# Generated by Django 3.2.16 on 2023-02-01 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mavzu', models.CharField(max_length=50)),
                ('matn', models.TextField()),
                ('vaqt', models.DateTimeField(default=datetime.datetime(2023, 2, 1, 16, 22, 58, 840644))),
            ],
        ),
    ]
