# Generated by Django 3.2.16 on 2023-02-02 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 16, 18, 29, 594181)),
        ),
    ]
